### ISSUE TITLE
OSGi - Vaadin-sass-compiler doesn't export all packages causing ClassNotFoundException

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#5642]
**Originally by _MarcB_**

___
This is the export statement of com.vaadin.sass-compiler:
Export-Package = com.vaadin.sass;version="0.9.10"

In OSGi export statements need to explicitly list each package, they do not automatically include subpackages. In this case com.vaadin.sass.internal or any of its subpackages will not be exported.

This is a problem because VaadinServlet in the com.vaadin.server bundle uses com.vaadin.sass.internal.ScssStylesheet. This causes a ClassNotFoundException to be thrown when trying to compile SASS on the fly when running in an OSGi environment.

The Require-Bundle: com.vaadin.sass-compiler statement in the com.vaadin.server bundles manifest only eliminates the need for import statements in the com.vaadin.server bundle, not a complete list of exports on the com.vaadin.sass-compiler bundle.

The easiest solution is probably to simply list all packages in the export statements list, however, it may be worth noting that exporting packages containing the word "internal" in OSGi is generally considered bad practice. A rename of "internal" would probably be a good idea in this case, assuming it doesn't break anything else.

Another solution that may work is to move ScssStylesheet out of internal and into the com.vaadin.sass package, but I'm unsure if there are any other usages of the .internal sass classes elsewhere in Vaadin.

Stacktrace for reference:
```
java.lang.NoClassDefFoundError: com/vaadin/sass/internal/ScssStylesheet
        at com.vaadin.server.VaadinServlet.compileScssOnTheFly(VaadinServlet.java:928)
        at com.vaadin.server.VaadinServlet.serveOnTheFlyCompiledScss(VaadinServlet.java:906)
        at com.vaadin.server.VaadinServlet.serveStaticResourcesInVAADIN(VaadinServlet.java:682)
        at com.vaadin.server.VaadinServlet.serveStaticResources(VaadinServlet.java:647)
        at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:298)
        at xxxxxxxxxxxxxxxxxxxxxxxxxx.SimpleVaadinServlet.service(SimpleVaadinServlet.java:211)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:848)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:684)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:501)
        at org.ops4j.pax.web.service.jetty.internal.HttpServiceServletHandler.doHandle(HttpServiceServletHandler.java:69)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137)
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:557)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1086)
        at org.ops4j.pax.web.service.jetty.internal.HttpServiceContext.doHandle(HttpServiceContext.java:240)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:428)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1020)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
        at org.ops4j.pax.web.service.jetty.internal.JettyServerHandlerCollection.handle(JettyServerHandlerCollection.java:77)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
        at org.eclipse.jetty.server.Server.handle(Server.java:366)
        at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:494)
        at org.eclipse.jetty.server.AbstractHttpConnection.headerComplete(AbstractHttpConnection.java:971)
        at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.headerComplete(AbstractHttpConnection.java:1033)
        at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:644)
        at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:235)
        at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)
        at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:667)
        at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:52)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: com.vaadin.sass.internal.ScssStylesheet
        at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:501)
        at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:421)
        at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:412)
        at org.eclipse.osgi.internal.baseadaptor.DefaultClassLoader.loadClass(DefaultClassLoader.java:107)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 33 more
```

___
 Imported from https://dev.vaadin.com/ issue #14615
