### ISSUE TITLE
NoClassDefFoundError: IOKit$IORegistryEntry

### ISSUE THREAD

**Issue by javier-godoy** [vaadin/framework#12320]
When upgrading a Vaadin 7.7.24 application to 7.7.26, the following exception is thrown upon application start:

```
java.lang.NoClassDefFoundError: com/sun/jna/platform/mac/IOKit$IORegistryEntry
at oshi.hardware.platform.mac.MacHardwareAbstractionLayer.createComputerSystem(MacHardwareAbstractionLayer.java:50)
at oshi.util.Memoizer$1.get(Memoizer.java:87)
at oshi.hardware.common.AbstractHardwareAbstractionLayer.getComputerSystem(AbstractHardwareAbstractionLayer.java:56)
at com.vaadin.pro.licensechecker.MachineId.getComputerId(MachineId.java:22)
at com.vaadin.pro.licensechecker.MachineId.get(MachineId.java:12)
at com.vaadin.pro.licensechecker.LicenseChecker.checkLicense(LicenseChecker.java:61)
at com.vaadin.pro.licensechecker.LicenseChecker.checkLicense(LicenseChecker.java:36)
at com.vaadin.server.VaadinServletService.verifyLicense(VaadinServletService.java:52)
at com.vaadin.server.VaadinServletService.<init>(VaadinServletService.java:45)
```

It seems to be related to https://github.com/oshi/oshi/issues/1384.
Indeed, it can be resolved by adding the following property in the POM (and mentioned in that issue):
 
```
<properties>
   <jna.version>5.6.0</jna.version>
</properties>
```

**Comment by TatuLund** [comment]
This seems to be issue only with OSX and does not occur e.g. in Windows.

**Comment by TatuLund** [comment]
My understanding is that this is not an issue in the framework, but something that can happen when the project has dependency to the same jar used by our license checker and producing conflict. This issue could happen also with Multi Platform Runtime product.
