### ISSUE TITLE
WebSocket Problem on Vaadin 8.1.0.beta1

### ISSUE THREAD

**Issue by pinonpierre** [vaadin/framework#9498]
Hi,

Web sockets (Push) doesn't work on Vaadin 8.1.0.beta1 and I have some exceptions in my logs.

No problem in Vaadin 8.0.6 and on Vaadin 7.7.7

I have embedded Jetty version 9.2.16.v20160414 but I tried with 9.2.21.v20170120 version and I have the same issue.

```
[17-06-07 14:30:23.976] [WARN ] (DefaultAsyncSupportResolver 588) Failed to create AsyncSupport class: class org.atmosphere.container.Jetty9AsyncSupportWithWebSocket, error: java.lang.reflect.InvocationTargetException 
[17-06-07 14:30:23.983] [ERROR] (DefaultAsyncSupportResolver 588) Real error: org.eclipse.jetty.websocket.server.WebSocketServerFactory.<init>(Ljavax/servlet/ServletContext;Lorg/eclipse/jetty/websocket/api/WebSocketPolicy;)V java.lang.NoSuchMethodError: org.eclipse.jetty.websocket.server.WebSocketServerFactory.<init>(Ljavax/servlet/ServletContext;Lorg/eclipse/jetty/websocket/api/WebSocketPolicy;)V
	at org.atmosphere.container.Jetty9AsyncSupportWithWebSocket$1.<init>(Jetty9AsyncSupportWithWebSocket.java:45)
	at org.atmosphere.container.Jetty9AsyncSupportWithWebSocket.<init>(Jetty9AsyncSupportWithWebSocket.java:45)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.atmosphere.cpr.DefaultAsyncSupportResolver.newCometSupport(DefaultAsyncSupportResolver.java:237)
	at org.atmosphere.cpr.DefaultAsyncSupportResolver.resolveWebSocket(DefaultAsyncSupportResolver.java:308)
	at org.atmosphere.cpr.DefaultAsyncSupportResolver.resolve(DefaultAsyncSupportResolver.java:294)
	at org.atmosphere.cpr.AtmosphereFramework.autoDetectContainer(AtmosphereFramework.java:2080)
	at org.atmosphere.cpr.AtmosphereFramework.init(AtmosphereFramework.java:914)
	at org.atmosphere.cpr.AtmosphereFramework.init(AtmosphereFramework.java:838)
	at com.vaadin.server.communication.PushRequestHandler.initAtmosphere(PushRequestHandler.java:216)
	at com.vaadin.server.communication.PushRequestHandler.<init>(PushRequestHandler.java:84)
	at com.vaadin.server.VaadinServletService.createRequestHandlers(VaadinServletService.java:53)
	at com.vaadin.server.VaadinService.init(VaadinService.java:195)
	at com.vaadin.server.VaadinServlet.createServletService(VaadinServlet.java:334)
	at com.vaadin.server.VaadinServlet.init(VaadinServlet.java:228)
	at org.eclipse.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:616)
	at org.eclipse.jetty.servlet.ServletHolder.initialize(ServletHolder.java:396)
	at org.eclipse.jetty.servlet.ServletHandler.initialize(ServletHandler.java:871)
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:298)
	at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1349)
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1342)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:741)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:505)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
	at org.eclipse.jetty.server.Server.start(Server.java:387)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
	at org.eclipse.jetty.server.Server.doStart(Server.java:354)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.teknux.jettybootstrap.JettyBootstrap.startServer(JettyBootstrap.java:146)
	at com.project.sm.app.Application.start(Application.java:136)
	at com.project.sm.app.Application.main(Application.java:76)

[17-06-07 14:30:23.997] [WARN ] (DefaultAsyncSupportResolver 588) Found multiple containers, please specify which one to use: org.atmosphere.container.Jetty7CometSupport, org.atmosphere.container.Jetty7CometSupport,  until you do, Atmosphere will use:class org.atmosphere.container.Jetty7CometSupport 
[17-06-07 14:30:23.998] [ERROR] (AtmosphereFramework         588) Failed to initialize Atmosphere Framework java.lang.NoClassDefFoundError: org/eclipse/jetty/continuation/ContinuationListener
	at java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671)
	at java.lang.Class.getConstructor0(Class.java:3075)
	at java.lang.Class.getDeclaredConstructor(Class.java:2178)
	at org.atmosphere.cpr.DefaultAsyncSupportResolver.newCometSupport(DefaultAsyncSupportResolver.java:236)
	at org.atmosphere.cpr.DefaultAsyncSupportResolver.resolveMultipleNativeSupportConflict(DefaultAsyncSupportResolver.java:336)
	at org.atmosphere.cpr.DefaultAsyncSupportResolver.resolveNativeCometSupport(DefaultAsyncSupportResolver.java:320)
	at org.atmosphere.cpr.DefaultAsyncSupportResolver.resolve(DefaultAsyncSupportResolver.java:299)
	at org.atmosphere.cpr.AtmosphereFramework.autoDetectContainer(AtmosphereFramework.java:2080)
	at org.atmosphere.cpr.AtmosphereFramework.init(AtmosphereFramework.java:914)
	at org.atmosphere.cpr.AtmosphereFramework.init(AtmosphereFramework.java:838)
	at com.vaadin.server.communication.PushRequestHandler.initAtmosphere(PushRequestHandler.java:216)
	at com.vaadin.server.communication.PushRequestHandler.<init>(PushRequestHandler.java:84)
	at com.vaadin.server.VaadinServletService.createRequestHandlers(VaadinServletService.java:53)
	at com.vaadin.server.VaadinService.init(VaadinService.java:195)
	at com.vaadin.server.VaadinServlet.createServletService(VaadinServlet.java:334)
	at com.vaadin.server.VaadinServlet.init(VaadinServlet.java:228)
	at org.eclipse.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:616)
	at org.eclipse.jetty.servlet.ServletHolder.initialize(ServletHolder.java:396)
	at org.eclipse.jetty.servlet.ServletHandler.initialize(ServletHandler.java:871)
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:298)
	at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1349)
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1342)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:741)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:505)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
	at org.eclipse.jetty.server.Server.start(Server.java:387)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
	at org.eclipse.jetty.server.Server.doStart(Server.java:354)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.teknux.jettybootstrap.JettyBootstrap.startServer(JettyBootstrap.java:146)
	at com.project.sm.app.Application.start(Application.java:136)
	at com.project.sm.app.Application.main(Application.java:76)
Caused by: java.lang.ClassNotFoundException: org.eclipse.jetty.continuation.ContinuationListener
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 39 common frames omitted

[17-06-07 14:30:24.000] [WARN ] (PushRequestHandler           86) Failed to initialize Atmosphere for Project. Push will not work. java.lang.RuntimeException: Atmosphere init failed
	at com.vaadin.server.communication.PushRequestHandler.initAtmosphere(PushRequestHandler.java:224)
	at com.vaadin.server.communication.PushRequestHandler.<init>(PushRequestHandler.java:84)
	at com.vaadin.server.VaadinServletService.createRequestHandlers(VaadinServletService.java:53)
	at com.vaadin.server.VaadinService.init(VaadinService.java:195)
	at com.vaadin.server.VaadinServlet.createServletService(VaadinServlet.java:334)
	at com.vaadin.server.VaadinServlet.init(VaadinServlet.java:228)
	at org.eclipse.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:616)
	at org.eclipse.jetty.servlet.ServletHolder.initialize(ServletHolder.java:396)
	at org.eclipse.jetty.servlet.ServletHandler.initialize(ServletHandler.java:871)
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:298)
	at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1349)
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1342)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:741)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:505)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
	at org.eclipse.jetty.server.Server.start(Server.java:387)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
	at org.eclipse.jetty.server.Server.doStart(Server.java:354)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.teknux.jettybootstrap.JettyBootstrap.startServer(JettyBootstrap.java:146)
	at com.project.sm.app.Application.start(Application.java:136)
	at com.project.sm.app.Application.main(Application.java:76)
Caused by: javax.servlet.ServletException: java.lang.NoClassDefFoundError: org/eclipse/jetty/continuation/ContinuationListener
	at org.atmosphere.cpr.AtmosphereFramework.init(AtmosphereFramework.java:955)
	at org.atmosphere.cpr.AtmosphereFramework.init(AtmosphereFramework.java:838)
	at com.vaadin.server.communication.PushRequestHandler.initAtmosphere(PushRequestHandler.java:216)
	... 27 common frames omitted
Caused by: java.lang.NoClassDefFoundError: org/eclipse/jetty/continuation/ContinuationListener
	at java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671)
	at java.lang.Class.getConstructor0(Class.java:3075)
	at java.lang.Class.getDeclaredConstructor(Class.java:2178)
	at org.atmosphere.cpr.DefaultAsyncSupportResolver.newCometSupport(DefaultAsyncSupportResolver.java:236)
	at org.atmosphere.cpr.DefaultAsyncSupportResolver.resolveMultipleNativeSupportConflict(DefaultAsyncSupportResolver.java:336)
	at org.atmosphere.cpr.DefaultAsyncSupportResolver.resolveNativeCometSupport(DefaultAsyncSupportResolver.java:320)
	at org.atmosphere.cpr.DefaultAsyncSupportResolver.resolve(DefaultAsyncSupportResolver.java:299)
	at org.atmosphere.cpr.AtmosphereFramework.autoDetectContainer(AtmosphereFramework.java:2080)
	at org.atmosphere.cpr.AtmosphereFramework.init(AtmosphereFramework.java:914)
	... 29 common frames omitted
Caused by: java.lang.ClassNotFoundException: org.eclipse.jetty.continuation.ContinuationListener
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 39 common frames omitted
```

**Comment by pinonpierre** [comment]
I also tried with Jetty 9.4.2.v20170220 but I have another issue (https://github.com/vaadin/framework/issues/8134)

At the end, It work works with 9.3.20.v20170531 Jetty version

**Comment by pinonpierre** [comment]
Fixed in 8.1.0 release
