### ISSUE TITLE
Support for Liferay 7.4.0 kernel version

### ISSUE THREAD

**Issue by mikke-alekstra** [vaadin/framework#12285]
Hello!

Liferay CE 7.4.0 GA1 was released with com.liferay.portal.kernel.util version 11.2.0 and this probably causes

`com.vaadin.server.ServiceException: java.lang.NoClassDefFoundError: com/liferay/portal/kernel/util/PortalClassLoaderUtil`

Could you please add support for 11.x series.

I adjusted server/bnd.bnd to [7.0.0,12.0.0) in my test bench and made a test compile. After this change Vaadin seemed to work fine with Liferay 7.4.0.

Thanks!
