### PR TITLE
Update Liferay kernel dependency range to [7.0.0,12.0.0)

### LINKED ISSUE #12285: Support for Liferay 7.4.0 kernel version
Hello!

Liferay CE 7.4.0 GA1 was released with com.liferay.portal.kernel.util version 11.2.0 and this probably causes

`com.vaadin.server.ServiceException: java.lang.NoClassDefFoundError: com/liferay/portal/kernel/util/PortalClassLoaderUtil`

Could you please add support for 11.x series.

I adjusted server/bnd.bnd to [7.0.0,12.0.0) in my test bench and made a test compile. After this change Vaadin seemed to work fine with Liferay 7.4.0.

Thanks!

### PR DESCRIPTION
**Pull request by TatuLund**
Fixes: https://github.com/vaadin/framework/issues/12285

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/12290)

### CODE REVIEW

**Review by Ansku — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/12290#-:-MZrMwOt5L7pkMdmc1DU:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @TatuLund)
